---
# tasks file for elasticsearch
- name: "Repository key url"
  apt_key:
    url: "{{ elasticsearch_apt_key_url }}"

- name: "Repository"
  apt_repository:
    repo: "{{ elasticsearch_apt_repo }}"
    filename: "elasticsearch"

- name: "Package"
  apt:
    name: "elasticsearch"
    update_cache: "yes"
    cache_valid_time: 3600

- name: "Configuration"
  template:
    src: "etc.elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    backup: true
  notify: "Restart ElasticSearch"

- name: "ElasticSearch Java heap configuration"
  lineinfile:
    dest: "/etc/elasticsearch/jvm.options"
    regexp: "-{{ item }}"
    line: "-{{ item }}{{ elasticsearch_jvm_heap }}"
    backup: true
  with_items:
    - "Xms"
    - "Xmx"
  notify: "Restart ElasticSearch"

- name: "Service"
  service:
    name: "elasticsearch"
    state: "started"
    enabled: "yes"
